services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: hotel_management_system
    plan: free 
    databaseName: hms_db
    user: hms_user
    postgresMajorVersion: "16" 

  # 2. The Django Web Application
  - type: web
    name: hotel_management_system_app
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn config.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: hotel_management_system
          property: connectionString
      - key: SECRET_KEY
        generateValue: true 
      - key: PYTHON_VERSION
        value: "3.12.3" 